
platform :ios, '9.0'

use_frameworks!

target 'CogsSDK_Example' do
  pod 'CogsSDK', :path => '../'

  target 'CogsSDK_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end
